In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

# (저자가 쓰는 방법)
# matplotlib 의 기본 scheme 말고 seaborn scheme 을 세팅하고,
#일일이 graph 의 font size 를 지정할 필요 없이 seaborn 의 font_scale 을 사용하면 편합니다.
plt.style.use('seaborn')
sns.set(font_scale=2.5)


import missingno as msno

# https://hong-yp-ml-records.tistory.com/14
# https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=youji4ever&logNo=221623491491

In [2]:
# Warning 메시지는 무시하겠다는 의미

#ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [3]:
# 도표와 같은 그림, 소리, 애니메이션 등을 Rich output 이라고 하는데,
# inline 이라고 적어야, 이 곳에 표시됨.
%matplotlib inline
# https://korbillgates.tistory.com/85

In [4]:
import os
print(os.getenv("HOME"))

In [5]:
df_train1 = pd.read_csv('/kaggle/input/titanic/train.csv')
df_test1 = pd.read_csv('/kaggle/input/titanic/test.csv')

In [6]:
df_train = pd.read_csv('../input/titanic/train.csv')
df_test = pd.read_csv('../input/titanic/test.csv')

In [7]:
# pandas.core.frame.DataFrame
print(type(df_train))

In [8]:
df_train

In [9]:
print(df_train)

In [10]:
df_train.columns

In [11]:
df_test.columns

* (train.csv) : PassengerId,**Survived**,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
* (test.csv ) : PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked

* PassengerId : 승객ID
* Survived : {0:사망, 1:생존}
* Pclass : {1:1등석, 2:2등석, 3:3등석}
* Name : 성명
* Sex : {male:'남성', female:'여성'}
* Age : 나이
* SibSp : 동승한 자매/배우자의 수
* Parch : 동승한 부모/자식의 수
* Ticket : 티켓 번호
* Fare : 승객 요금
* Cabin : 방 호수
* Embarked : 탑승지 {C='셰르부르', Q='퀸즈타운', S='사우샘프턴'}

In [12]:
df_train.head()

In [13]:
df_train1.head()

In [14]:
df_test.head()

In [15]:
df_test1.head()

In [16]:
df_train.info()

* 총 891건
* Age : 714건, Cabin (방 번호): 204건, Embarked (탑승지) : 889건

* Age 와 Fare (승객요금)은 float64

In [17]:
df_test.info()

* 총 418건
* Age : 332건, Cabin (방 번호): 91건

* Age 와 Fare (승객요금)은 float64

In [18]:
df_train.describe()

In [19]:
df_test.describe()

In [57]:
# 그래프의 크기 지정
plt.figure(figsize=(8, 8))

# Heatmap 설정
sns.heatmap(df_train.corr(), linewidths=0.1, vmax=0.5, cmap=plt.cm.gist_heat,
            linecolor='white', annot=True)

# 렌더링
plt.show()

In [20]:
# https://ashhyun.github.io/kaggle/Titanic_1/
plt.style.use('ggplot')
sns.set()
sns.set_palette("Set2")

def chart(dataset, feature):
    dead = dataset[dataset['Survived']==0][feature].value_counts()
    alive = dataset[dataset['Survived']==1][feature].value_counts()
    df = pd.DataFrame([dead, alive])
    df.index = ['Dead','Alive']
    df.plot(kind = 'bar', stacked=True)
    
# 등석별 사망,생존 비
chart(df_train, 'Pclass')

In [21]:
# 등석별 사망,생존 비
chart(df_train, 'Pclass')

In [22]:
# 성별 사망,생존 비
chart(df_train, 'Sex')

In [23]:
# 자매 또는 배우자수 별 사망,생존 비
chart(df_train, 'SibSp')

* 자매 또는 배우자수가 0 인 생존율이 가장 높음

In [24]:
# 자매 또는 배우자수 별 사망,생존 비 (1명 제외)
temp1 = df_train[(df_train['SibSp'] >= 1)]
chart(temp1, 'SibSp')

* 자매 또는 배우자 0명 다음으로, 자매 또는 배우자 1명이 가장 높음

In [25]:
# 자매 또는 배우자수 별 사망,생존 비 (1명 제외)
temp2 = df_train[(df_train['SibSp'] >= 2)]
chart(temp2, 'SibSp')

* 자매 또는 배우자수 3명 이상부터 생존율 크게 떨어짐
* 자매 또는 배우자수가 5명 이상은 몰살

#aaa
##aaa
###aaa
####aaa
#####aaa
######aaa

# aaa1
## aaa2
### aaa3
#### aaa4
##### aaa5
###### aaa6
####### aaa7
######## aaa8


**aaaa**
*bbbb*

** aaa **
* bbb *

> cccc
> dddd

[xxxx](http://)

[dddd](http://)
![](http://)eeee



* ffff
1. gggg
# hhhh


# xxx

# 1.1 Null data check

In [26]:
for col in df_train.columns:
    msg = 'column: {:>10}\t Percent of NaN value: {:.2f}%'.format(col, 100 * (df_train[col].isnull().sum() / df_train[col].shape[0]))
    print(msg)

In [27]:
for col in df_test.columns:
    msg = 'column: {:>10}\t Percent of NaN value: {:.2f}%'.format(col, 100 * (df_test[col].isnull().sum() / df_test[col].shape[0]))
    print(msg)

* train 과 test 모두, Age는 20% 정도, Cabin (방 호수)은 80% 가 값이 없고,
* Embarked (탑승지) 는 train 에서만 0.22%
* Fare (승객요금) 는 test 에서 0.24% 널임.

MANO 라는 라이브러리 ???

missingno 모듈을 사용하면, 시각적으로 결측치를 파악할 수 있다.

In [28]:
msno.matrix(df=df_train.iloc[:, :], figsize=(8, 8), color=(0.8, 0.5, 0.2))

In [29]:
msno.bar(df=df_train.iloc[:, :], figsize=(8,8), color=(0.8, 0.5, 0.2))

msno.bar(df=df_test.iloc[:, :], figsize=(8,8), color=(0.1, 0.6, 0.8))

* test 데이타도, train 데이타와 비슷한 비율로,
        Age 는 80%만 존재하고, Cabin (방 호수)은 20%만 존재함.

# 1.2 Target label 확인

* target label 이 어떤 distribution 을 가지고 있는지 확인해 봐야 합니다.
* 지금 같은 binary classification 문제의 경우에서,
   1 과 0 의 분포가 어떠냐에 따라, 모델의 평가방법이 달라 질 수 있습니다.

In [30]:
f, ax = plt.subplots(1, 2, figsize=(18, 8))

df_train['Survived'].value_counts().plot.pie(explode=[0, 0.1], autopct='%1.1f%%', ax=ax[0], shadow=True)
ax[0].set_title('Pie plot - Survived')
ax[0].set_ylabel('')

sns.countplot('Survived', data=df_train, ax=ax[1])
ax[1].set_title('Count plot - Survived')

plt.show()

* 38.4% 가 살아남았습니다.
* target label 의 분포가 제법 균일(balanced)합니다.

      불균일 할 경우,
          예를 들어 100 중 1이 99개, 0 이 1개인 경우에는...  모델이 모든 것을 1이라고 해도 99%가 된다.
          0을 찾는 문제라면, 이 모델은 원하는 결과를 줄 수 없게 된다.

# 2. Exploratory data analysis

* 데이터는 너무 많고, 적절한 시각화가 필요
* 시각화 라이브러리는 matplotlib, seaborn, plotly 등이 있음.

## 2.1 Pclass

* Pclass 는 ordinal, 서수형 데이터
    카테고리 이면서, 순서가 있는 데이터 타입
* Pclass 에 따른 생존율 차이
    엑셀의 피봇 차트와 유사한 작업
    pandas dataframe 에서는 grouby 를 사용하면 쉽게 할 수 있음.
    pivot 이라는 메서드도 있음.
* 아래와 같이 count()를 하면, 각 class 에 몇 명이 있는지 확인할 수 있으며,
  sum()을 하면, 216명 중 생존한(survived=1) 사람의 총합을 주게 됨.

In [31]:
# Pclass (등석)과 Survived(DoA)을 대상으로, 등석별 카운트
df_train[['Pclass', 'Survived']].groupby(['Pclass'], as_index=True).count()

In [32]:
# Pclass (등석)과 Survived(DoA)을 대상으로, 등석별 생존자 수 (사망자는 0이라서 sum()에 추가 안됨)
df_train[['Pclass', 'Survived']].groupby(['Pclass'], as_index=True).sum()

In [33]:
# pandas 의 crosstab
pd.crosstab(df_train['Pclass'], df_train['Survived'], margins=True).style.background_gradient(cmap='summer_r')

### grouped 객체에 mean() 을 하게 되면, 각 클래스별 생존률을 얻을 수 있습니다.
### class 1 이면 아래와 같습니다.

In [34]:
df_train[['Pclass', 'Survived']].groupby(['Pclass'], as_index=True).mean().sort_values(by='Survived', ascending=False).plot.bar()

1등석, 2등석, 3등석 순으로 생존율이 높다.

In [35]:
# seaborn 의 countplot

y_position = 1.02

f, ax = plt.subplots(1, 2, figsize=(18, 8))

df_train['Pclass'].value_counts().plot.bar(color=['#CD7F32','#FFDF00','#D3D3D3'], ax=ax[0])
ax[0].set_title('Number of Passengers By Pclass', y=y_position)
ax[0].set_ylabel('Count')

sns.countplot('Pclass', hue='Survived', data=df_train, ax=ax[1])
ax[1].set_title('Pclass: Dead or Alive', y=y_position)

plt.show()

* Pclass (등석)가 높을수록 생존율이 높음 (Pclass 1,2,3순으로 63%, 48%, 25% 임)
* 생존에 Pclass가 큰 영향을 미친다고 생각할 수 있으며,
   나중에 모델을 세울 때, 이 feature를 사용해야 한다고 판단할 수 있음.

## 2.2 Sex

In [36]:
f, ax = plt.subplots(1, 2, figsize=(18, 8))

df_train[['Sex', 'Survived']].groupby(['Sex'], as_index=True).mean().plot.bar(ax=ax[0])
ax[0].set_title('Survived vs Sex')

sns.countplot('Sex', hue='Survived', data=df_train, ax=ax[1])
ax[1].set_title('Sex: Survived vs Dead')
plt.show()

* 탑승객 중 남성 비율이 높음.

* 남성의 사망율이 매우 높음
* 여성의 사망율은 남성에 비하여 매우 낮음.

In [37]:
df_train[['Sex', 'Survived']].groupby(['Sex'], as_index=False).mean().sort_values(by='Survived', ascending=False)

#### 여성은 74% 생존한 반면, 남성은 19% 만 생존

In [38]:
pd.crosstab(df_train['Sex'], df_train['Survived'], margins=True).style.background_gradient(cmap='summer_r')

Sex 도 예측 모델에 쓰일 중요한 feature 임을 알 수 있음.

## 2.3 Both Sex and Pclass

* Pclass 와 Sex 에 따라, 생존이 어떻게 달라지는지 확인한다.
* seaborn 의 factorplot 을 이용하면, 손쉽게 3차원 그래프를 볼 수 있음.

In [39]:
sns.factorplot('Pclass', 'Survived', hue='Sex', data=df_train, size=6, aspect=1.5)

* 여성이 남성 보다 생존율이 월등히 높음.
* 1등석, 2등석 여성은 생존율이 크게 높은 반면,
    3등석 여성은 상대적으로 크게 떨어짐.

* 2등석, 3등석 남성 사망율 매우 높음.

* 성별에 관계 없이, Pclass 가 높을수록 생존율이 높지만,
        1등석 남성의 생존율이 전체 생존율 대비 크게 높다고 볼 수는 없음.
        2등석과 3등석 남성에 비하여 상대적으로 높음.

In [40]:
# 위의 그래프는 hue 대신 column 으로 하면 아래와 같아진다.
sns.factorplot(x='Sex', y='Survived', col='Pclass', data=df_train, satureation=.5,size=9, aspect=1)

* 1,2등석 여성 생존율 매우 높음
* 2,3등석 남성 사망율 매우 높음
* 1등석 남성의 생존율은, 2,3등석 남성에 비하여 상대적으로 높음.

* 3등석 여성의 생존율은, 1등석 남성에 비하여 약간 높은 수준임.

## 2.4 Age

In [41]:
print('제일 나이 많은 탑승객 : {:.1f} Years'.format(df_train['Age'].max()))
print('제일 어린 탑승객 : {:.1f} Years'.format(df_train['Age'].min()))
print('탑승객 평균 나이 : {:.1f} Years'.format(df_train['Age'].mean()))

In [42]:
fig, ax = plt.subplots(1, 1, figsize=(9, 5))
sns.kdeplot(df_train[df_train['Survived'] == 1]['Age'], ax=ax)
sns.kdeplot(df_train[df_train['Survived'] == 0]['Age'], ax=ax)
plt.legend(['Survived == 1', 'Survived == 0'])
plt.show()

* 10대 중후반 기준으로,
    어린 아이 생존율이 사망율 보다 높음
    
* 10대 중후반 기준으로,
    20대 초반까지 사망율이 생존율 보다 높음.
    
* 이후 연령대는 생존율과 사망율이 비슷함.

In [43]:
# Age distribution withing classes
plt.figure(figsize=(8, 6))
df_train['Age'][df_train['Pclass'] == 1].plot(kind='kde')
df_train['Age'][df_train['Pclass'] == 2].plot(kind='kde')
df_train['Age'][df_train['Pclass'] == 3].plot(kind='kde')

plt.xlabel('Age')
plt.title('Age Distribution within classes')
plt.legend(['1st Class', '2nd Class', '3rd Class'])

Pclass 가 높을수록, 중년 이후의 생존율이 높음을 알 수 있다.

Pclass 가 낮아도, 젊으면 생존율이 가장 높음을 알 수 있다.

In [44]:
cummulate_survival_ratio = []
for i in range(1, 80):
    cummulate_survival_ratio.append(df_train[df_train['Age'] < i]['Survived'].sum() / len(df_train[df_train['Age'] < i]['Survived']))
    
plt.figure(figsize=(7, 7))
plt.plot(cummulate_survival_ratio)
plt.title('Survival rate change depending on range of Age', y=1.02)
plt.ylabel('Survival rate')
plt.xlabel('Range of Age(0~x)')
plt.show()

* 나이가 어릴수록 생존율이 월등히 높아짐을 알 수 있다.
* 연령이 중요한 feature 로 쓰일 수 있음.

## 2.5 Pclass , Sex , Age

dddd

In [45]:
f,ax=plt.subplots(1,2,figsize=(18,8))

sns.violinplot("Pclass","Age", hue="Survived", data=df_train, scale='count', split=True,ax=ax[0])
ax[0].set_title('Pclass and Age vs Survived')
ax[0].set_yticks(range(0,110,10))

sns.violinplot("Sex","Age", hue="Survived", data=df_train, scale='count', split=True,ax=ax[1])
ax[1].set_title('Sex and Age vs Survived')
ax[1].set_yticks(range(0,110,10))

plt.show()

## 2.6 Embarked
* Embarked 는 탑승한 항구를 나타냅니다.
* 탑승한 곳에 따른 생존율을 본다.

In [46]:
f, ax = plt.subplots(1, 1, figsize=(7, 7))
df_train[['Embarked', 'Survived']].groupby(['Embarked'], as_index=True).mean().sort_values(by='Survived', ascending=False).plot.bar(ax=ax)

* 생존율은 비슷
* 모델에 영향을 얼마나 미칠 지 모르나, 일단 사용
* 모델을 만들고 나면, 사용한 feature가 중요한 역할을 했는지 확인 가능
* 다른 feature로 split 하여 다시 살펴봄

In [47]:
f,ax=plt.subplots(2, 2, figsize=(20,15))
sns.countplot('Embarked', data=df_train, ax=ax[0,0])
ax[0,0].set_title('(1) No. Of Passengers Boarded')
sns.countplot('Embarked', hue='Sex', data=df_train, ax=ax[0,1])
ax[0,1].set_title('(2) Male-Female Split for Embarked')
sns.countplot('Embarked', hue='Survived', data=df_train, ax=ax[1,0])
ax[1,0].set_title('(3) Embarked vs Survived')
sns.countplot('Embarked', hue='Pclass', data=df_train, ax=ax[1,1])
ax[1,1].set_title('(4) Embarked vs Pclass')
plt.subplots_adjust(wspace=0.2, hspace=0.5)
plt.show()

* Fig(1) : S 에서 가장 많이 탑승
* Fig(2) : C 와 Q는 남녀비율 비슷하고, S는 남성이 2배 비율
* Fig(3) : S 는 절반만 생존. 생존비율 낮음
* Fig(4) : Class로 split 해서 보니, C가 ???

## 2.7 Family = SibSp (형제 자매) + Parch (부모 자녀)
* SibSp 와 Parch 를 합하면 Family 가 됨.

In [48]:
df_train['FamilySize'] = df_train['SibSp'] + df_train['Parch'] + 1 # 자신을 포함해야하니 1을 더합니다
df_test['FamilySize'] = df_test['SibSp'] + df_test['Parch'] + 1 # 자신을 포함해야하니 1을 더합니다

In [49]:
print("Maximum size of Family: ", df_train['FamilySize'].max())
print("Minimum size of Family: ", df_train['FamilySize'].min())

In [50]:
# FamilySize 와 생존의 관계

f,ax=plt.subplots(1, 3, figsize=(40,10))
sns.countplot('FamilySize', data=df_train, ax=ax[0])
ax[0].set_title('(1) No. Of Passengers Boarded', y=1.02)

sns.countplot('FamilySize', hue='Survived', data=df_train, ax=ax[1])
ax[1].set_title('(2) Survived countplot depending on FamilySize',  y=1.02)

df_train[['FamilySize', 'Survived']].groupby(['FamilySize'], as_index=True).mean().sort_values(by='Survived', ascending=False).plot.bar(ax=ax[2])
ax[2].set_title('(3) Survived rate depending on FamilySize',  y=1.02)

plt.subplots_adjust(wspace=0.2, hspace=0.5)
plt.show()

* Fig(1) : 가족크기가 1~11명까지 있음.
            대부분 1명이고, 그 다음으로 2,3,4명
* Fig(2), (3) : 가족 크기에 따른 생존비율.
                 가족 4명인 경우가 가장 생존확률이 높음.
                  가족 수가 많아질수록 (5,6,7,8,11명) 생존확률 낮아짐.
                 너무 작아도(1명), 너무 커도(5,6,8,11명) 생존확률 적음.
                 3~4명 가족이 생존확률 높음.

In [51]:
fig, ax = plt.subplots(1, 1, figsize=(8, 8))
g = sns.distplot(df_train['Fare'], color='b', label='Skewness : {:.2f}'.format(df_train['Fare'].skew()), ax=ax)
g = g.legend(loc='best')

* distribution이 매우 비대칭 (high skewness)
   이대로 모델에 넣으면 잘못 학습 할 수 있음.
   몇 개 없는 outlier에 대해 너무 민감하게 반응하다면, 실제 예측시에 좋지 않은 결과를 낳을 수 있음.
* outlier의 영향을 줄이기 위해, Fare 에 log를 취한다.
* pandas의 유용한 기능 사용
   dataFrame의 특정 columns에 공통된 작업(함수)를 적용하고 싶다며,
    아래의 map 또는 apply를 사용하면 쉽게 적용 가능.
* 지금 원하는 것은, Fare columns의 데이터 모두에 log값을 취하는 것인데,
  lambda 함수를 이용해 간단한 로그를 적용하는 함수를, map에 인수로 넣어주면,
  Fare columns 데이터에 그대로 적용됨.

In [52]:
# 아래 줄은 뒤늦게 발견하였습니다. 13번째 강의에 언급되니, 일단 따라치시고 넘어가면 됩니다.
df_test.loc[df_test.Fare.isnull(), 'Fare'] = df_test['Fare'].mean() # testset 에 있는 nan value 를 평균값으로 치환합니다.

df_train['Fare'] = df_train['Fare'].map(lambda i: np.log(i) if i > 0 else 0)
df_test['Fare'] = df_test['Fare'].map(lambda i: np.log(i) if i > 0 else 0)

# 위에 뭔가 문제 있음.

In [53]:
fig, ax = plt.subplots(1, 1, figsize=(8, 8))
g = sns.distplot(df_train['Fare'], color='b', label='Skewness : {:.2f}'.format(df_train['Fare'].skew()), ax=ax)
g = g.legend(loc='best')

* log를 취하니, 비대칭성이 많이 사라짐.
* 이러한 작업을 통하여, 모델이 좀 더 좋은 성능을 내도록 할 수 있다.
* feature engineering 에 들어가는 부분인데, 여기서 작업함.
* 모델을 학습시키기 위해, 성능을 향상시키기 위해,
  feature들을 조작하거나, 새로운 feature를 추가하는 것을 feature engineering 이라고 함.

# 2.9 Cabin

* 이 feature는 NaN이 대략 80% 이므로,
   생존에 영향을 미칠 중요한 정보를 얻어내기가 쉽지 않다.
  따라서 모델에 포함시키지 않겠다.

In [54]:
df_train.head()

# 2.10 Ticket
* 이 feature는 NaN이 없음.
  string data 이므로 어떤 작업을 해주어야 실제 모델에 사용 가능. 아이디어가 필요.

In [55]:
df_train['Ticket'].value_counts()

* ticket number 는 매우 다양함.